### ISSUE TITLE
Help requested on flashing the board

### ISSUE THREAD

**Issue by samxplogs** [OzInFl/CLIPPER1#2]
Hi,

Your project look awesome and I wanted to give a try hence I bought a ESP32-WT32-SC01 PLUS with the screen that look like yours. However I have hard time flashing it.

Could you share a bit on your method to flash it ?
I have attempt using Visual Studio Code + PlatformIO but I am running with an issue. I am wondering if the compiled project is not taking too much size than the acctual size on the board.

Thanks for your help :)

 *  Executing task: platformio run --target upload 

Processing WT (platform: espressif32; board: um_tinys3; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/um_tinys3.html
PLATFORM: Espressif 32 (6.3.2) > Unexpected Maker TinyS3
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20009.0 (2.0.9) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - tool-mkfatfs @ 2.0.1 
 - tool-mklittlefs @ 1.203.210628 (2.3) 
 - tool-mkspiffs @ 2.230.0 (2.30) 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 41 compatible libraries
Scanning dependencies...
Dependency Graph
|-- AsyncTCP @ 1.1.1
|-- LovyanGFX @ 0.4.18
|-- lvgl @ 8.3.8+sha.1c5d4b0
|-- SmartRC-CC1101-Driver-Lib @ 2.5.7+sha.b8c6af4
|-- ArduinoJson @ 6.20.0
|-- SdFat @ 2.2.2+sha.57900b2
|-- NewRemoteSwitch @ 0.0.0+20230706224405.sha.c3ca4cb
|-- ESP32-audioI2S @ 2.1.0
|-- SPIFFS @ 2.0.0
|-- ArduinoOTA @ 2.0.0
|-- ESP32 BLE Arduino @ 2.0.0
|-- SD @ 2.0.0
|-- SPI @ 2.0.0
|-- Update @ 2.0.0
|-- WebServer @ 2.0.0
|-- WiFi @ 2.0.0
Building in release mode
Retrieving maximum program size .pio/build/WT/firmware.elf
Checking size .pio/build/WT/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
**Error: The program size (3688793 bytes) is greater than maximum allowed (3342336 bytes)**
RAM:   [=====   *** [checkprogsize] Explicit exit, status 1
  ]  52.9% (used 173380 bytes from 327680 bytes)
Flash: [==========]  110.4% (used 3688793 bytes from 3342336 bytes)

**Comment by Bob337** [comment]
Hi if you want to flash ESP32-WT32-SC01 PLUS use aplication called "ESPHome-Flasher-1.4.0-Windows-x64.exe"
visit this repo 
https://github.com/esphome/esphome-flasher/releases/tag/1.4.0

If you want to program and compile you own projects go to https://8ms.xyz/appshop
register and play

**Comment by OzInFl** [comment]
Hey Sam, We ran into that same issue and it is due to the version of Expressif that is installed on your platforms area in Platformio.
See if you can have better luck by clicking on the Platformio Home Page - Then Click Platforms on the left side Toolbar, then the Embedded Tab on top then search for "espressif" then click on the result and try to install 5.0.0  (you are at 6.3.2)

Here is my compile debug:
Processing WT (platform: espressif32@5.0.0; board: um_tinys3; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via -v, --verbose option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/um_tinys3.html
PLATFORM: Espressif 32 (5.0.0) > Unexpected Maker TinyS3
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 
framework-arduinoespressif32 @ 3.20003.220626 (2.0.3) 
tool-esptoolpy @ 1.30300.0 (3.3.0)
toolchain-riscv32-esp @ 8.4.0+2021r2-patch3
toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 40 compatible libraries
Scanning dependencies...
Dependency Graph
|-- AsyncTCP @ 1.1.1
|-- LovyanGFX @ 0.4.18
|-- lvgl @ 8.3.7+sha.3de61c7
|-- SmartRC-CC1101-Driver-Lib @ 2.5.7+sha.b8c6af4
|-- ArduinoJson @ 6.20.0
|-- SdFat @ 2.2.2+sha.57900b2
|-- NewRemoteSwitch @ 0.0.0+20230627215226.sha.c3ca4cb
|-- ESP32-audioI2S @ 2.1.0
|-- SPIFFS @ 2.0.0
|-- ArduinoOTA @ 2.0.0
|-- ESP32 BLE Arduino @ 2.0.0
|-- SD @ 2.0.0
|-- SPI @ 2.0.0
|-- Update @ 2.0.0
|-- WebServer @ 2.0.0
|-- WiFi @ 2.0.0

**Comment by OzInFl** [comment]
You can hit me up on discord as well here: Discord: https://discord.gg/Dmpme8ph88

**Comment by OzInFl** [comment]
Also for flashing,  I Use the USB-C connector and short the GPIO0 pin on the debug port of the LCD to gnd before powerup, this will put it in DFU mode, then you should be able to upload the firmware. The first time you flash it correctly it will take about 20 seconds before the LCD comes up due to the initialization of SPIFFS, subsequent power ups are instant, just the first time it may trick you into thinking that it didnt work as the screen will be blank)

**Comment by OzInFl** [comment]
![image](https://github.com/OzInFl/CLIPPER1/assets/53567373/053a8194-cee2-4987-a352-6f9113ea70dd)

**Comment by OzInFl** [comment]
This is what my platforms area looks like:

![image](https://github.com/OzInFl/CLIPPER1/assets/53567373/d59ddfcb-c242-4c09-b890-5f54f831df81)

**Comment by OzInFl** [comment]
> Hi,
> 
> Your project look awesome and I wanted to give a try hence I bought a ESP32-WT32-SC01 PLUS with the screen that look like yours. However I have hard time flashing it.
> 
> Could you share a bit on your method to flash it ? I have attempt using Visual Studio Code + PlatformIO but I am running with an issue. I am wondering if the compiled project is not taking too much size than the acctual size on the board.
> 
> Thanks for your help :)
> 
> * Executing task: platformio run --target upload
> 
> ## Processing WT (platform: espressif32; board: um_tinys3; framework: arduino)
> Verbose mode can be enabled via `-v, --verbose` option CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/um_tinys3.html PLATFORM: Espressif 32 (6.3.2) > Unexpected Maker TinyS3 HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa) PACKAGES:
> 
> * framework-arduinoespressif32 @ 3.20009.0 (2.0.9)
> * tool-esptoolpy @ 1.40501.0 (4.5.1)
> * tool-mkfatfs @ 2.0.1
> * tool-mklittlefs @ 1.203.210628 (2.3)
> * tool-mkspiffs @ 2.230.0 (2.30)
> * toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
> * toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
>   LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
>   LDF Modes: Finder ~ chain, Compatibility ~ soft
>   Found 41 compatible libraries
>   Scanning dependencies...
>   Dependency Graph
>   |-- AsyncTCP @ 1.1.1
>   |-- LovyanGFX @ 0.4.18
>   |-- lvgl @ 8.3.8+sha.1c5d4b0
>   |-- SmartRC-CC1101-Driver-Lib @ 2.5.7+sha.b8c6af4
>   |-- ArduinoJson @ 6.20.0
>   |-- SdFat @ 2.2.2+sha.57900b2
>   |-- NewRemoteSwitch @ 0.0.0+20230706224405.sha.c3ca4cb
>   |-- ESP32-audioI2S @ 2.1.0
>   |-- SPIFFS @ 2.0.0
>   |-- ArduinoOTA @ 2.0.0
>   |-- ESP32 BLE Arduino @ 2.0.0
>   |-- SD @ 2.0.0
>   |-- SPI @ 2.0.0
>   |-- Update @ 2.0.0
>   |-- WebServer @ 2.0.0
>   |-- WiFi @ 2.0.0
>   Building in release mode
>   Retrieving maximum program size .pio/build/WT/firmware.elf
>   Checking size .pio/build/WT/firmware.elf
>   Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
>   **Error: The program size (3688793 bytes) is greater than maximum allowed (3342336 bytes)**
>   RAM:   [=====   *** [checkprogsize] Explicit exit, status 1
>   ]  52.9% (used 173380 bytes from 327680 bytes)
>   Flash: [==========]  110.4% (used 3688793 bytes from 3342336 bytes)

See the thread below for some help with this..
